### ISSUE TITLE
[QUESTION] How to handle subscribing in sub-components?

### ISSUE THREAD

**Issue by danawoodman** [lukeed/vegemite#5]
For a React/Preact app, how would you go about subscribing to a part of the state tree in a sub component?

Say I have the state:

```ts
const store = vegemite({
  users: [
    { id: 1, name: 'Foo' },
  ]
});
```

How could I subscribe to any changes to the user object only and not the rest of the state? I don't want the sub component to re-render if some other state I don't care about changes. Is this possible?

**Comment by lukeed** [comment]
There are a couple ways to go about this. You can:

1) use smaller stores - they have tiny footprints and very little reason not to throw around multiple Vegemite stores in the same app, or even the same page. For example, I'll always have a store for the current user and another for the `todos` or something they're looking at.

2) you can attach listen() subscribers for the events you know you want to listen to. For exams, if you have a generic `users:changed` event that you dispatch all changes to, then you can just listen to that elsewhere(s)

```js
store.listen('users:change', state => {
  // ...
})
```

You can hoist this subscriber function and attach it to multiple topics (as listeners) if you have more than one.

3) you can use a generic/global listener and manually compare the `users` key since that's what you care about:

```js
import dequal from 'dequal';

store.listen((state, previous) => {
  if (!dequal(state.users, previous.users)) {
    // changed 
  }
})
```

Hope that helps!

**Comment by lukeed** [comment]
Closing for now – if you still have questions please don't hesitate!

**Comment by franky47** [comment]
This is the way I do it in React:
- Pass an accessor function
- Optionally pass a function to transform the value to test for changes (eg: JSON.stringify)

```ts
import React from 'react'
import { State, store } from './store'

export function useStateFragment<T>(
  accessor: (state: State) => T,
  equalityTransform: (a: T) => any = a => a
) {
  const [value, setValue] = React.useState(
    accessor(store.state)
  )
  React.useEffect(() => {
    const unsubscribe = store.listen(
      (newState, oldState) => {
        const oldValue = accessor(oldState)
        const newValue = accessor(newState)
        if (equalityTransform(oldValue) !== equalityTransform(newValue)) {
          setValue(newValue)
        }
      }
    )
    return unsubscribe
  }, [])
  return value
}
```

Usage:
```tsx
const firstTodo = useStateFragment(state => state.todos[0])
const username = useStateFragment(state => state.user.profile.firstName)
```

**Comment by danawoodman** [comment]
Thanks for the replies!
